name: ci

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker registry
        uses: docker/login-action@v1
        with:
          registry: <registry> # Remplacez par votre URL de registre
          username: ${{ secrets.REGISTRY_USERNAME }} # Remplacez par votre nom d'utilisateur de registre
          password: ${{ secrets.REGISTRY_PASSWORD }} # Remplacez par votre mot de passe de registre

      - name: Build and push Docker images
        env:
          DOCKER_BUILDKIT: '1'
          COMPOSE_DOCKER_CLI_BUILD: '1'
        run: |
          docker-compose build

          # Tag and push the built images to the registry
          docker-compose push

      - name: Deploy with Docker Compose
        env:
          DOCKER_BUILDKIT: '1'
          COMPOSE_DOCKER_CLI_BUILD: '1'
        run: |
          # Install Docker Compose if not already installed
          if ! command -v docker-compose &> /dev/null; then
            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi

          # Deploy the stack using Docker Compose
          docker-compose up -d
