name: ci

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Log in to Docker registry
        uses: docker/login-action@v1
        with:
          registry: docker.io # Remplacez par votre URL de registre
          username: ${{ secrets.REGISTRY_USERNAME }} # Remplacez par votre nom d'utilisateur de registre
          password: ${{ secrets.REGISTRY_PASSWORD }} # Remplacez par votre mot de passe de registre

      - name: Build and push Docker images
        run: |
          docker-compose build

          # Tag and push the built images to the registry
          docker-compose push

      - name: Deploy with Docker Compose
        run: |
          # Deploy the stack using Docker Compose
          docker-compose up -d
